export const colors = {
  primary: '#FF5E89',
  primaryLight: '#FF809F',
  primaryDark: '#D93C67',
  pinkSoft: '#FFEBF0',
  pinkMuted: '#FFF0F5',
  bgCream: '#FFF8F8',
  background: '#FFF8F8',
  surface: '#FFFFFF',
  surfaceCard: '#FFFFFF',
  darkChocolate: '#3B2C30',
  darkMuted: '#584146',
  textPrimary: '#3B2C30',
  textSecondary: '#7A666A',
  textMuted: '#9E8A8E',
  borderPink: '#FBCFE8',
  borderDark: '#3B2C30',
  borderLight: '#F3E8EC',
  peach: '#FED8BF',
  gold: '#F59E0B',
  yellowSoft: '#FEF3C7',
  blueSoft: '#BAE6FD',
  greenSoft: '#D1FAE5',
  purpleSoft: '#EDE9FE',
  success: '#10B981',
  danger: '#EF4444',
  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',
  overlay: 'rgba(59, 44, 48, 0.4)',
} as const;

export type ColorToken = keyof typeof colors;
